# Generated by Django 3.2.19 on 2023-05-31 16:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import flyapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('all', 'All'), ('digital-influence', 'Digital Influence'), ('courses', 'courses'), ('software', 'software')], default='software', max_length=120)),
                ('product_name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=20, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, validators=[flyapp.models.validate_decimal])),
                ('influencer_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rating', models.PositiveIntegerField()),
                ('mssg', models.TextField()),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=120)),
                ('city', models.TextField()),
                ('region', models.TextField()),
                ('zip_code', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('promo_code', models.CharField(blank=True, max_length=20, null=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyapp.product')),
            ],
        ),
    ]
