# Generated by Django 3.2.19 on 2023-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
